//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteSFATestWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-test2.arabesque.ro:8000/sap/bc/srt/rfc/sap/ztest_itab/900/ztest_itab/z" +
            "test_itab")]
        public string LiteSFATestWebService_WEBTable_ZTEST_ITABService {
            get {
                return ((string)(this["LiteSFATestWebService_WEBTable_ZTEST_ITABService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-TEST1A.arabesque.ro:8081/sap/bc/srt/rfc/sap/zwbs_zintrarimarfa/900/zwb" +
            "s_zintrarimarfa/zwbs_zintrarimarfa")]
        public string LiteSFATestWebService_WebNecesar1_ZWBS_ZNECESAR1Service {
            get {
                return ((string)(this["LiteSFATestWebService_WebNecesar1_ZWBS_ZNECESAR1Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-TEST1A.arabesque.ro:8081/sap/bc/srt/rfc/sap/ztbl_webservice/900/ztbl_w" +
            "ebservice/ztbl_webservice")]
        public string LiteSFATestWebService_SapWebServices_ZTBL_WEBSERVICE {
            get {
                return ((string)(this["LiteSFATestWebService_SapWebServices_ZTBL_WEBSERVICE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-TEST1A.arabesque.ro:8081/sap/bc/srt/rfc/sap/zclp_webservice/900/zclp_w" +
            "ebservice/zclp_webservice")]
        public string LiteSFATestWebService_SAPWebServiceCLP_ZCLP_WEBSERVICEService {
            get {
                return ((string)(this["LiteSFATestWebService_SAPWebServiceCLP_ZCLP_WEBSERVICEService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd3a.arabesque.ro:8033/sap/bc/srt/rfc/sap/zwbs_sal_av/900/zwbs_sal_av" +
            "/zwbs_sal_av")]
        public string LiteSFATestWebService_WebServiceSalarizareAG_ZWBS_SAL_AV {
            get {
                return ((string)(this["LiteSFATestWebService_WebServiceSalarizareAG_ZWBS_SAL_AV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wsi.bizpack.ro/service.php")]
        public string LiteSFATestWebService_SMSService_SMSServiceService {
            get {
                return ((string)(this["LiteSFATestWebService_SMSService_SMSServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-TEST1A.arabesque.ro:8081/sap/bc/srt/rfc/sap/zwbs_semiactivi/900/zwbs_s" +
            "emiactivi/zwbs_semiactivi")]
        public string LiteSFATestWebService_ClientiSemiactivi_ZWBS_SEMIACTIVI {
            get {
                return ((string)(this["LiteSFATestWebService_ClientiSemiactivi_ZWBS_SEMIACTIVI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd5a.arabesque.ro:8035/sap/bc/srt/rfc/sap/zwbs_sal_av/900/zwbs_sal_av" +
            "/zwbs_sal_av")]
        public string LiteSFATestWebService_SalarizareAG_ZWBS_SAL_AV {
            get {
                return ((string)(this["LiteSFATestWebService_SalarizareAG_ZWBS_SAL_AV"]));
            }
        }
    }
}
