//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteSFATestWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-test2.arabesque.ro:8000/sap/bc/srt/rfc/sap/ztest_itab/900/ztest_itab/z" +
            "test_itab")]
        public string LiteSFATestWebService_WEBTable_ZTEST_ITABService {
            get {
                return ((string)(this["LiteSFATestWebService_WEBTable_ZTEST_ITABService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-QAS1A.arabesque.ro:8082/sap/bc/srt/rfc/sap/zwbs_zintrarimarfa/900/zwbs" +
            "_zintrarimarfa/zwbs_zintrarimarfa")]
        public string LiteSFATestWebService_WebNecesar1_ZWBS_ZNECESAR1Service {
            get {
                return ((string)(this["LiteSFATestWebService_WebNecesar1_ZWBS_ZNECESAR1Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-QAS1A.arabesque.ro:8082/sap/bc/srt/rfc/sap/zclp_webservice/900/zclp_we" +
            "bservice/zclp_webservice")]
        public string LiteSFATestWebService_SAPWebServiceCLP_ZCLP_WEBSERVICEService {
            get {
                return ((string)(this["LiteSFATestWebService_SAPWebServiceCLP_ZCLP_WEBSERVICEService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd5a.arabesque.ro:8035/sap/bc/srt/rfc/sap/zwbs_sal_av/900/zwbs_sal_av" +
            "/zwbs_sal_av")]
        public string LiteSFATestWebService_WebServiceSalarizareAG_ZWBS_SAL_AV {
            get {
                return ((string)(this["LiteSFATestWebService_WebServiceSalarizareAG_ZWBS_SAL_AV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.bizpack.ro/wsi/service.php")]
        public string LiteSFATestWebService_SMSService_SMSServiceService {
            get {
                return ((string)(this["LiteSFATestWebService_SMSService_SMSServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-QAS1A.arabesque.ro:8082/sap/bc/srt/rfc/sap/zwbs_semiactivi/900/zwbs_se" +
            "miactivi/zwbs_semiactivi")]
        public string LiteSFATestWebService_ClientiSemiactivi_ZWBS_SEMIACTIVI {
            get {
                return ((string)(this["LiteSFATestWebService_ClientiSemiactivi_ZWBS_SEMIACTIVI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd5a.arabesque.ro:8035/sap/bc/srt/rfc/sap/zwbs_sal_av/900/zwbs_sal_av" +
            "/zwbs_sal_av")]
        public string LiteSFATestWebService_SalarizareAG_ZWBS_SAL_AV {
            get {
                return ((string)(this["LiteSFATestWebService_SalarizareAG_ZWBS_SAL_AV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-QAS1A.arabesque.ro:8082/sap/bc/srt/rfc/sap/ztbl_webservice/900/ztbl_we" +
            "bservice/ztbl_webservice")]
        public string LiteSFATestWebService_SAPWebServices_ZTBL_WEBSERVICE {
            get {
                return ((string)(this["LiteSFATestWebService_SAPWebServices_ZTBL_WEBSERVICE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-QAS1A.arabesque.ro:8082/sap/bc/srt/rfc/sap/zfg_instr_plata/900/zfg_ins" +
            "tr_plata/zfg_instr_plata")]
        public string LiteSFATestWebService_PlataNeincasate_ZFG_INSTR_PLATA {
            get {
                return ((string)(this["LiteSFATestWebService_PlataNeincasate_ZFG_INSTR_PLATA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bg-test01.budmax.bg:8003/sap/bc/srt/rfc/sap/ztbl_webservice/900/ztbl_webse" +
            "rvice/ztbl_webservice")]
        public string LiteSFATestWebService_SapWs_test_bg_budmax_ZTBL_WEBSERVICE {
            get {
                return ((string)(this["LiteSFATestWebService_SapWs_test_bg_budmax_ZTBL_WEBSERVICE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-QAS1A.arabesque.ro:8082/sap/bc/srt/rfc/sap/zws_custodie/900/zwbs_custo" +
            "die/zwbs_custodie")]
        public string LiteSFATestWebService_SAPWSCustodie_ZWS_CUSTODIE {
            get {
                return ((string)(this["LiteSFATestWebService_SAPWSCustodie_ZWS_CUSTODIE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zws_salarizare_2019/900/zws" +
            "_salarizare_2019/zws_salarizare_2019")]
        public string LiteSFATestWebService_Salarizare2019_ZWS_SALARIZARE_2019 {
            get {
                return ((string)(this["LiteSFATestWebService_Salarizare2019_ZWS_SALARIZARE_2019"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd6a.arabesque.ro:8036/sap/bc/srt/rfc/sap/zws_sal_ka_2019/900/zws_sal" +
            "_ka_2019/zws_sal_ka_2019")]
        public string LiteSFATestWebService_SalarizareKA_ZWS_SAL_KA_2019 {
            get {
                return ((string)(this["LiteSFATestWebService_SalarizareKA_ZWS_SAL_KA_2019"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd6a.arabesque.ro:8036/sap/bc/srt/rfc/sap/zws_cl_fact_avsd/900/zws_cl" +
            "_fact_avsd/zws_cl_fact_avsd")]
        public string LiteSFATestWebService_SapWSPierderiVanzri_ZWS_CL_FACT_AVSD {
            get {
                return ((string)(this["LiteSFATestWebService_SapWSPierderiVanzri_ZWS_CL_FACT_AVSD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-QAS1A.arabesque.ro:8082/sap/bc/srt/rfc/sap/zwms_ul10_get_stock_arab/90" +
            "0/zwms_ul10_get_stock_arab/zwms_ul10_get_stock_arab")]
        public string LiteSFATestWebService_SapWsCabluri05_ZWMS_UL10_GET_STOCK_ARAB {
            get {
                return ((string)(this["LiteSFATestWebService_SapWsCabluri05_ZWMS_UL10_GET_STOCK_ARAB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SAP-QAS1A.arabesque.ro:8082/sap/bc/srt/rfc/sap/zws_sal_cva/900/zws_sal_cva" +
            "/zws_sal_cva")]
        public string LiteSFATestWebService_SalarizareCVA_ZWS_SAL_CVA {
            get {
                return ((string)(this["LiteSFATestWebService_SalarizareCVA_ZWS_SAL_CVA"]));
            }
        }
    }
}
