//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LiteSFATestWebService.SapWsClp {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZCLP_WEBSERVICE", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZCLP_WEBSERVICE : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZcreazaCaDlOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZcreazaStoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZaprobaComandaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZlivrareStoIesireOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZstergeStoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZCLP_WEBSERVICE() {
            this.Url = global::LiteSFATestWebService.Properties.Settings.Default.LiteSFATestWebService_SAPWebServiceCLP_ZCLP_WEBSERVICEService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZcreazaCaDlCompletedEventHandler ZcreazaCaDlCompleted;
        
        /// <remarks/>
        public event ZcreazaStoCompletedEventHandler ZcreazaStoCompleted;
        
        /// <remarks/>
        public event ZaprobaComandaCompletedEventHandler ZaprobaComandaCompleted;
        
        /// <remarks/>
        public event ZlivrareStoIesireCompletedEventHandler ZlivrareStoIesireCompleted;
        
        /// <remarks/>
        public event ZstergeStoCompletedEventHandler ZstergeStoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZCLP_WEBSERVICE:ZcreazaCaDlReque" +
            "st", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZcreazaCaDlResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZcreazaCaDlResponse ZcreazaCaDl([System.Xml.Serialization.XmlElementAttribute("ZcreazaCaDl", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZcreazaCaDl ZcreazaCaDl1) {
            object[] results = this.Invoke("ZcreazaCaDl", new object[] {
                        ZcreazaCaDl1});
            return ((ZcreazaCaDlResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZcreazaCaDlAsync(ZcreazaCaDl ZcreazaCaDl1) {
            this.ZcreazaCaDlAsync(ZcreazaCaDl1, null);
        }
        
        /// <remarks/>
        public void ZcreazaCaDlAsync(ZcreazaCaDl ZcreazaCaDl1, object userState) {
            if ((this.ZcreazaCaDlOperationCompleted == null)) {
                this.ZcreazaCaDlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZcreazaCaDlOperationCompleted);
            }
            this.InvokeAsync("ZcreazaCaDl", new object[] {
                        ZcreazaCaDl1}, this.ZcreazaCaDlOperationCompleted, userState);
        }
        
        private void OnZcreazaCaDlOperationCompleted(object arg) {
            if ((this.ZcreazaCaDlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZcreazaCaDlCompleted(this, new ZcreazaCaDlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZCLP_WEBSERVICE:ZcreazaStoReques" +
            "t", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZcreazaStoResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZcreazaStoResponse ZcreazaSto([System.Xml.Serialization.XmlElementAttribute("ZcreazaSto", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZcreazaSto ZcreazaSto1) {
            object[] results = this.Invoke("ZcreazaSto", new object[] {
                        ZcreazaSto1});
            return ((ZcreazaStoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZcreazaStoAsync(ZcreazaSto ZcreazaSto1) {
            this.ZcreazaStoAsync(ZcreazaSto1, null);
        }
        
        /// <remarks/>
        public void ZcreazaStoAsync(ZcreazaSto ZcreazaSto1, object userState) {
            if ((this.ZcreazaStoOperationCompleted == null)) {
                this.ZcreazaStoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZcreazaStoOperationCompleted);
            }
            this.InvokeAsync("ZcreazaSto", new object[] {
                        ZcreazaSto1}, this.ZcreazaStoOperationCompleted, userState);
        }
        
        private void OnZcreazaStoOperationCompleted(object arg) {
            if ((this.ZcreazaStoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZcreazaStoCompleted(this, new ZcreazaStoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZCLP_WEBSERVICE:ZaprobaComandaRe" +
            "quest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZaprobaComandaResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZaprobaComandaResponse ZaprobaComanda([System.Xml.Serialization.XmlElementAttribute("ZaprobaComanda", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZaprobaComanda ZaprobaComanda1) {
            object[] results = this.Invoke("ZaprobaComanda", new object[] {
                        ZaprobaComanda1});
            return ((ZaprobaComandaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZaprobaComandaAsync(ZaprobaComanda ZaprobaComanda1) {
            this.ZaprobaComandaAsync(ZaprobaComanda1, null);
        }
        
        /// <remarks/>
        public void ZaprobaComandaAsync(ZaprobaComanda ZaprobaComanda1, object userState) {
            if ((this.ZaprobaComandaOperationCompleted == null)) {
                this.ZaprobaComandaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZaprobaComandaOperationCompleted);
            }
            this.InvokeAsync("ZaprobaComanda", new object[] {
                        ZaprobaComanda1}, this.ZaprobaComandaOperationCompleted, userState);
        }
        
        private void OnZaprobaComandaOperationCompleted(object arg) {
            if ((this.ZaprobaComandaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZaprobaComandaCompleted(this, new ZaprobaComandaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZCLP_WEBSERVICE:ZlivrareStoIesir" +
            "eRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZlivrareStoIesireResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZlivrareStoIesireResponse ZlivrareStoIesire([System.Xml.Serialization.XmlElementAttribute("ZlivrareStoIesire", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZlivrareStoIesire ZlivrareStoIesire1) {
            object[] results = this.Invoke("ZlivrareStoIesire", new object[] {
                        ZlivrareStoIesire1});
            return ((ZlivrareStoIesireResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZlivrareStoIesireAsync(ZlivrareStoIesire ZlivrareStoIesire1) {
            this.ZlivrareStoIesireAsync(ZlivrareStoIesire1, null);
        }
        
        /// <remarks/>
        public void ZlivrareStoIesireAsync(ZlivrareStoIesire ZlivrareStoIesire1, object userState) {
            if ((this.ZlivrareStoIesireOperationCompleted == null)) {
                this.ZlivrareStoIesireOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZlivrareStoIesireOperationCompleted);
            }
            this.InvokeAsync("ZlivrareStoIesire", new object[] {
                        ZlivrareStoIesire1}, this.ZlivrareStoIesireOperationCompleted, userState);
        }
        
        private void OnZlivrareStoIesireOperationCompleted(object arg) {
            if ((this.ZlivrareStoIesireCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZlivrareStoIesireCompleted(this, new ZlivrareStoIesireCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZCLP_WEBSERVICE:ZstergeStoReques" +
            "t", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZstergeStoResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZstergeStoResponse ZstergeSto([System.Xml.Serialization.XmlElementAttribute("ZstergeSto", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZstergeSto ZstergeSto1) {
            object[] results = this.Invoke("ZstergeSto", new object[] {
                        ZstergeSto1});
            return ((ZstergeStoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZstergeStoAsync(ZstergeSto ZstergeSto1) {
            this.ZstergeStoAsync(ZstergeSto1, null);
        }
        
        /// <remarks/>
        public void ZstergeStoAsync(ZstergeSto ZstergeSto1, object userState) {
            if ((this.ZstergeStoOperationCompleted == null)) {
                this.ZstergeStoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZstergeStoOperationCompleted);
            }
            this.InvokeAsync("ZstergeSto", new object[] {
                        ZstergeSto1}, this.ZstergeStoOperationCompleted, userState);
        }
        
        private void OnZstergeStoOperationCompleted(object arg) {
            if ((this.ZstergeStoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZstergeStoCompleted(this, new ZstergeStoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcreazaCaDl {
        
        private decimal vIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VId {
            get {
                return this.vIdField;
            }
            set {
                this.vIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcreazaCaDlResponse {
        
        private string vOkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOk {
            get {
                return this.vOkField;
            }
            set {
                this.vOkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcreazaSto {
        
        private decimal vIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VId {
            get {
                return this.vIdField;
            }
            set {
                this.vIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcreazaStoResponse {
        
        private string vMessField;
        
        private string vOkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VMess {
            get {
                return this.vMessField;
            }
            set {
                this.vMessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOk {
            get {
                return this.vOkField;
            }
            set {
                this.vOkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaprobaComanda {
        
        private string pernrChField;
        
        private decimal vIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PernrCh {
            get {
                return this.pernrChField;
            }
            set {
                this.pernrChField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VId {
            get {
                return this.vIdField;
            }
            set {
                this.vIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaprobaComandaResponse {
        
        private string vMessField;
        
        private string vOkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VMess {
            get {
                return this.vMessField;
            }
            set {
                this.vMessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOk {
            get {
                return this.vOkField;
            }
            set {
                this.vOkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZlivrareStoIesire {
        
        private string vEbelnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VEbeln {
            get {
                return this.vEbelnField;
            }
            set {
                this.vEbelnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZlivrareStoIesireResponse {
        
        private string vOkField;
        
        private string vVbelnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOk {
            get {
                return this.vOkField;
            }
            set {
                this.vOkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VVbeln {
            get {
                return this.vVbelnField;
            }
            set {
                this.vVbelnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstergeSto {
        
        private string pernrChField;
        
        private string stareField;
        
        private decimal vIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PernrCh {
            get {
                return this.pernrChField;
            }
            set {
                this.pernrChField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Stare {
            get {
                return this.stareField;
            }
            set {
                this.stareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VId {
            get {
                return this.vIdField;
            }
            set {
                this.vIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstergeStoResponse {
        
        private string vErrField;
        
        private string vOkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VErr {
            get {
                return this.vErrField;
            }
            set {
                this.vErrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOk {
            get {
                return this.vOkField;
            }
            set {
                this.vOkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ZcreazaCaDlCompletedEventHandler(object sender, ZcreazaCaDlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZcreazaCaDlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZcreazaCaDlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZcreazaCaDlResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZcreazaCaDlResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ZcreazaStoCompletedEventHandler(object sender, ZcreazaStoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZcreazaStoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZcreazaStoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZcreazaStoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZcreazaStoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ZaprobaComandaCompletedEventHandler(object sender, ZaprobaComandaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZaprobaComandaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZaprobaComandaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZaprobaComandaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZaprobaComandaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ZlivrareStoIesireCompletedEventHandler(object sender, ZlivrareStoIesireCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZlivrareStoIesireCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZlivrareStoIesireCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZlivrareStoIesireResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZlivrareStoIesireResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ZstergeStoCompletedEventHandler(object sender, ZstergeStoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZstergeStoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZstergeStoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZstergeStoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZstergeStoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591