//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LiteSFATestWebService.WebServiceSalarizareAV {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZWBS_SAL_AV", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZWBS_SAL_AV : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZgetSalavOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZWBS_SAL_AV() {
            this.Url = global::LiteSFATestWebService.Properties.Settings.Default.LiteSFATestWebService_WebServiceSalarizareAG_ZWBS_SAL_AV;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZgetSalavCompletedEventHandler ZgetSalavCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWBS_SAL_AV:ZgetSalavRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZgetSalavResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZgetSalavResponse ZgetSalav([System.Xml.Serialization.XmlElementAttribute("ZgetSalav", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZgetSalav ZgetSalav1) {
            object[] results = this.Invoke("ZgetSalav", new object[] {
                        ZgetSalav1});
            return ((ZgetSalavResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZgetSalavAsync(ZgetSalav ZgetSalav1) {
            this.ZgetSalavAsync(ZgetSalav1, null);
        }
        
        /// <remarks/>
        public void ZgetSalavAsync(ZgetSalav ZgetSalav1, object userState) {
            if ((this.ZgetSalavOperationCompleted == null)) {
                this.ZgetSalavOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZgetSalavOperationCompleted);
            }
            this.InvokeAsync("ZgetSalav", new object[] {
                        ZgetSalav1}, this.ZgetSalavOperationCompleted, userState);
        }
        
        private void OnZgetSalavOperationCompleted(object arg) {
            if ((this.ZgetSalavCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZgetSalavCompleted(this, new ZgetSalavCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZgetSalav {
        
        private string anField;
        
        private string divizieField;
        
        private Ztmarja[] gtMarjaAvField;
        
        private Zsalav3[] gtOuttabAvField;
        
        private Zspenalty[] gtPenalty99Field;
        
        private ZprocincSapreport[] gtProcenteAvField;
        
        private Zstcf[] gtTcfAvField;
        
        private ZtprsSapreport[] gtTprsdsAvField;
        
        private Zpernr[] itPernrField;
        
        private string lunaField;
        
        private string ulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string An {
            get {
                return this.anField;
            }
            set {
                this.anField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Divizie {
            get {
                return this.divizieField;
            }
            set {
                this.divizieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ztmarja[] GtMarjaAv {
            get {
                return this.gtMarjaAvField;
            }
            set {
                this.gtMarjaAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zsalav3[] GtOuttabAv {
            get {
                return this.gtOuttabAvField;
            }
            set {
                this.gtOuttabAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zspenalty[] GtPenalty99 {
            get {
                return this.gtPenalty99Field;
            }
            set {
                this.gtPenalty99Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZprocincSapreport[] GtProcenteAv {
            get {
                return this.gtProcenteAvField;
            }
            set {
                this.gtProcenteAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zstcf[] GtTcfAv {
            get {
                return this.gtTcfAvField;
            }
            set {
                this.gtTcfAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZtprsSapreport[] GtTprsdsAv {
            get {
                return this.gtTprsdsAvField;
            }
            set {
                this.gtTprsdsAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zpernr[] ItPernr {
            get {
                return this.itPernrField;
            }
            set {
                this.itPernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Luna {
            get {
                return this.lunaField;
            }
            set {
                this.lunaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ul {
            get {
                return this.ulField;
            }
            set {
                this.ulField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Ztmarja {
        
        private string pernrField;
        
        private decimal venitMarjaField;
        
        private decimal marjaAnCurentField;
        
        private decimal marjaAnPrecedField;
        
        private decimal procMarjaField;
        
        private decimal coefRealizField;
        
        private string enameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VenitMarja {
            get {
                return this.venitMarjaField;
            }
            set {
                this.venitMarjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal MarjaAnCurent {
            get {
                return this.marjaAnCurentField;
            }
            set {
                this.marjaAnCurentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal MarjaAnPreced {
            get {
                return this.marjaAnPrecedField;
            }
            set {
                this.marjaAnPrecedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ProcMarja {
            get {
                return this.procMarjaField;
            }
            set {
                this.procMarjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CoefRealiz {
            get {
                return this.coefRealizField;
            }
            set {
                this.coefRealizField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ename {
            get {
                return this.enameField;
            }
            set {
                this.enameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zpernr {
        
        private string pernrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZtprsSapreport {
        
        private string pernrField;
        
        private string codnivelField;
        
        private decimal pondereField;
        
        private decimal targetcantField;
        
        private string vrkmeField;
        
        private decimal targetvalField;
        
        private string waersField;
        
        private decimal targetcantrField;
        
        private decimal targetvalrField;
        
        private decimal realizaretargetField;
        
        private decimal targetponderatField;
        
        private decimal coefcorField;
        
        private decimal venitgiField;
        
        private decimal venitprField;
        
        private decimal venitfinalField;
        
        private string grupMatField;
        
        private string codnivel2Field;
        
        private string vkgrpField;
        
        private string descriereField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codnivel {
            get {
                return this.codnivelField;
            }
            set {
                this.codnivelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Pondere {
            get {
                return this.pondereField;
            }
            set {
                this.pondereField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Targetcant {
            get {
                return this.targetcantField;
            }
            set {
                this.targetcantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vrkme {
            get {
                return this.vrkmeField;
            }
            set {
                this.vrkmeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Targetval {
            get {
                return this.targetvalField;
            }
            set {
                this.targetvalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Waers {
            get {
                return this.waersField;
            }
            set {
                this.waersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Targetcantr {
            get {
                return this.targetcantrField;
            }
            set {
                this.targetcantrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Targetvalr {
            get {
                return this.targetvalrField;
            }
            set {
                this.targetvalrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Realizaretarget {
            get {
                return this.realizaretargetField;
            }
            set {
                this.realizaretargetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Targetponderat {
            get {
                return this.targetponderatField;
            }
            set {
                this.targetponderatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Coefcor {
            get {
                return this.coefcorField;
            }
            set {
                this.coefcorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Venitgi {
            get {
                return this.venitgiField;
            }
            set {
                this.venitgiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Venitpr {
            get {
                return this.venitprField;
            }
            set {
                this.venitprField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Venitfinal {
            get {
                return this.venitfinalField;
            }
            set {
                this.venitfinalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrupMat {
            get {
                return this.grupMatField;
            }
            set {
                this.grupMatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codnivel2 {
            get {
                return this.codnivel2Field;
            }
            set {
                this.codnivel2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vkgrp {
            get {
                return this.vkgrpField;
            }
            set {
                this.vkgrpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descriere {
            get {
                return this.descriereField;
            }
            set {
                this.descriereField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zstcf {
        
        private string pernrField;
        
        private decimal venitTprField;
        
        private byte targetPField;
        
        private byte targetRField;
        
        private decimal coefAfField;
        
        private decimal venitTcfField;
        
        private string enameField;
        
        private string tipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VenitTpr {
            get {
                return this.venitTprField;
            }
            set {
                this.venitTprField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public byte TargetP {
            get {
                return this.targetPField;
            }
            set {
                this.targetPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public byte TargetR {
            get {
                return this.targetRField;
            }
            set {
                this.targetRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CoefAf {
            get {
                return this.coefAfField;
            }
            set {
                this.coefAfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VenitTcf {
            get {
                return this.venitTcfField;
            }
            set {
                this.venitTcfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ename {
            get {
                return this.enameField;
            }
            set {
                this.enameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tip {
            get {
                return this.tipField;
            }
            set {
                this.tipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZprocincSapreport {
        
        private string pernrField;
        
        private string kunnrField;
        
        private string name1Field;
        
        private decimal perIField;
        
        private decimal perIaField;
        
        private decimal perIbField;
        
        private decimal prcIField;
        
        private decimal prcIaField;
        
        private decimal prcIbField;
        
        private decimal perIiField;
        
        private decimal perIiaField;
        
        private decimal perIibField;
        
        private decimal prcIiField;
        
        private decimal prcIiaField;
        
        private decimal prcIibField;
        
        private decimal perIiiField;
        
        private decimal perIiiaField;
        
        private decimal perIiibField;
        
        private decimal prcIiiField;
        
        private decimal prcIiiaField;
        
        private decimal prcIiibField;
        
        private decimal perIvField;
        
        private decimal perIvaField;
        
        private decimal perIvbField;
        
        private decimal prcIvField;
        
        private decimal prcIvaField;
        
        private decimal prcIvbField;
        
        private decimal perVField;
        
        private decimal perVaField;
        
        private decimal perVbField;
        
        private decimal prcVField;
        
        private decimal prcVaField;
        
        private decimal prcVbField;
        
        private decimal perViField;
        
        private decimal perViaField;
        
        private decimal perVibField;
        
        private decimal prcViField;
        
        private decimal prcViaField;
        
        private decimal prcVibField;
        
        private decimal perViiField;
        
        private decimal perViiaField;
        
        private decimal perViibField;
        
        private decimal prcViiField;
        
        private decimal prcViiaField;
        
        private decimal prcViibField;
        
        private decimal perTotalField;
        
        private decimal prcTotalField;
        
        private string waersField;
        
        private decimal venitprField;
        
        private decimal venitfinalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Kunnr {
            get {
                return this.kunnrField;
            }
            set {
                this.kunnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerI {
            get {
                return this.perIField;
            }
            set {
                this.perIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerIa {
            get {
                return this.perIaField;
            }
            set {
                this.perIaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerIb {
            get {
                return this.perIbField;
            }
            set {
                this.perIbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcI {
            get {
                return this.prcIField;
            }
            set {
                this.prcIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcIa {
            get {
                return this.prcIaField;
            }
            set {
                this.prcIaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcIb {
            get {
                return this.prcIbField;
            }
            set {
                this.prcIbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerIi {
            get {
                return this.perIiField;
            }
            set {
                this.perIiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerIia {
            get {
                return this.perIiaField;
            }
            set {
                this.perIiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerIib {
            get {
                return this.perIibField;
            }
            set {
                this.perIibField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcIi {
            get {
                return this.prcIiField;
            }
            set {
                this.prcIiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcIia {
            get {
                return this.prcIiaField;
            }
            set {
                this.prcIiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcIib {
            get {
                return this.prcIibField;
            }
            set {
                this.prcIibField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerIii {
            get {
                return this.perIiiField;
            }
            set {
                this.perIiiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerIiia {
            get {
                return this.perIiiaField;
            }
            set {
                this.perIiiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerIiib {
            get {
                return this.perIiibField;
            }
            set {
                this.perIiibField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcIii {
            get {
                return this.prcIiiField;
            }
            set {
                this.prcIiiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcIiia {
            get {
                return this.prcIiiaField;
            }
            set {
                this.prcIiiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcIiib {
            get {
                return this.prcIiibField;
            }
            set {
                this.prcIiibField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerIv {
            get {
                return this.perIvField;
            }
            set {
                this.perIvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerIva {
            get {
                return this.perIvaField;
            }
            set {
                this.perIvaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerIvb {
            get {
                return this.perIvbField;
            }
            set {
                this.perIvbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcIv {
            get {
                return this.prcIvField;
            }
            set {
                this.prcIvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcIva {
            get {
                return this.prcIvaField;
            }
            set {
                this.prcIvaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcIvb {
            get {
                return this.prcIvbField;
            }
            set {
                this.prcIvbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerV {
            get {
                return this.perVField;
            }
            set {
                this.perVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerVa {
            get {
                return this.perVaField;
            }
            set {
                this.perVaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerVb {
            get {
                return this.perVbField;
            }
            set {
                this.perVbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcV {
            get {
                return this.prcVField;
            }
            set {
                this.prcVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcVa {
            get {
                return this.prcVaField;
            }
            set {
                this.prcVaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcVb {
            get {
                return this.prcVbField;
            }
            set {
                this.prcVbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerVi {
            get {
                return this.perViField;
            }
            set {
                this.perViField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerVia {
            get {
                return this.perViaField;
            }
            set {
                this.perViaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerVib {
            get {
                return this.perVibField;
            }
            set {
                this.perVibField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcVi {
            get {
                return this.prcViField;
            }
            set {
                this.prcViField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcVia {
            get {
                return this.prcViaField;
            }
            set {
                this.prcViaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcVib {
            get {
                return this.prcVibField;
            }
            set {
                this.prcVibField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerVii {
            get {
                return this.perViiField;
            }
            set {
                this.perViiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerViia {
            get {
                return this.perViiaField;
            }
            set {
                this.perViiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerViib {
            get {
                return this.perViibField;
            }
            set {
                this.perViibField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcVii {
            get {
                return this.prcViiField;
            }
            set {
                this.prcViiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcViia {
            get {
                return this.prcViiaField;
            }
            set {
                this.prcViiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcViib {
            get {
                return this.prcViibField;
            }
            set {
                this.prcViibField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PerTotal {
            get {
                return this.perTotalField;
            }
            set {
                this.perTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PrcTotal {
            get {
                return this.prcTotalField;
            }
            set {
                this.prcTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Waers {
            get {
                return this.waersField;
            }
            set {
                this.waersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Venitpr {
            get {
                return this.venitprField;
            }
            set {
                this.venitprField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Venitfinal {
            get {
                return this.venitfinalField;
            }
            set {
                this.venitfinalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zspenalty {
        
        private string pernrField;
        
        private decimal venitPenalizatField;
        
        private decimal coefPenalizareField;
        
        private decimal valNeincasataField;
        
        private string enameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VenitPenalizat {
            get {
                return this.venitPenalizatField;
            }
            set {
                this.venitPenalizatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CoefPenalizare {
            get {
                return this.coefPenalizareField;
            }
            set {
                this.coefPenalizareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValNeincasata {
            get {
                return this.valNeincasataField;
            }
            set {
                this.valNeincasataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ename {
            get {
                return this.enameField;
            }
            set {
                this.enameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsalav3 {
        
        private string mandtField;
        
        private string tippartField;
        
        private string dentipField;
        
        private string anvField;
        
        private string lunaField;
        
        private string bzirkField;
        
        private string prctrField;
        
        private string vkgrpField;
        
        private string pernrField;
        
        private string enameField;
        
        private decimal venitgiField;
        
        private decimal venitprField;
        
        private decimal venittcfField;
        
        private decimal venitmarjaField;
        
        private decimal penalty99Field;
        
        private decimal venitfinalField;
        
        private string waersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tippart {
            get {
                return this.tippartField;
            }
            set {
                this.tippartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dentip {
            get {
                return this.dentipField;
            }
            set {
                this.dentipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Anv {
            get {
                return this.anvField;
            }
            set {
                this.anvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Luna {
            get {
                return this.lunaField;
            }
            set {
                this.lunaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bzirk {
            get {
                return this.bzirkField;
            }
            set {
                this.bzirkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Prctr {
            get {
                return this.prctrField;
            }
            set {
                this.prctrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vkgrp {
            get {
                return this.vkgrpField;
            }
            set {
                this.vkgrpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ename {
            get {
                return this.enameField;
            }
            set {
                this.enameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Venitgi {
            get {
                return this.venitgiField;
            }
            set {
                this.venitgiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Venitpr {
            get {
                return this.venitprField;
            }
            set {
                this.venitprField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Venittcf {
            get {
                return this.venittcfField;
            }
            set {
                this.venittcfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Venitmarja {
            get {
                return this.venitmarjaField;
            }
            set {
                this.venitmarjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Penalty99 {
            get {
                return this.penalty99Field;
            }
            set {
                this.penalty99Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Venitfinal {
            get {
                return this.venitfinalField;
            }
            set {
                this.venitfinalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Waers {
            get {
                return this.waersField;
            }
            set {
                this.waersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZgetSalavResponse {
        
        private Ztmarja[] gtMarjaAvField;
        
        private Zsalav3[] gtOuttabAvField;
        
        private Zspenalty[] gtPenalty99Field;
        
        private ZprocincSapreport[] gtProcenteAvField;
        
        private Zstcf[] gtTcfAvField;
        
        private ZtprsSapreport[] gtTprsdsAvField;
        
        private Zpernr[] itPernrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ztmarja[] GtMarjaAv {
            get {
                return this.gtMarjaAvField;
            }
            set {
                this.gtMarjaAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zsalav3[] GtOuttabAv {
            get {
                return this.gtOuttabAvField;
            }
            set {
                this.gtOuttabAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zspenalty[] GtPenalty99 {
            get {
                return this.gtPenalty99Field;
            }
            set {
                this.gtPenalty99Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZprocincSapreport[] GtProcenteAv {
            get {
                return this.gtProcenteAvField;
            }
            set {
                this.gtProcenteAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zstcf[] GtTcfAv {
            get {
                return this.gtTcfAvField;
            }
            set {
                this.gtTcfAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZtprsSapreport[] GtTprsdsAv {
            get {
                return this.gtTprsdsAvField;
            }
            set {
                this.gtTprsdsAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zpernr[] ItPernr {
            get {
                return this.itPernrField;
            }
            set {
                this.itPernrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ZgetSalavCompletedEventHandler(object sender, ZgetSalavCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZgetSalavCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZgetSalavCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZgetSalavResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZgetSalavResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591