//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LiteSFATestWebService.SAPWSBudmax {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZTBL_WEBSERVICE", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZTBL_WEBSERVICE : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZcreazaComandaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZcalcTrapOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZactDiscMaximOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZgetPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZstareComandaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZTBL_WEBSERVICE() {
            this.Url = global::LiteSFATestWebService.Properties.Settings.Default.LiteSFATestWebService_SapWs_test_bg_budmax_ZTBL_WEBSERVICE;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZcreazaComandaCompletedEventHandler ZcreazaComandaCompleted;
        
        /// <remarks/>
        public event ZcalcTrapCompletedEventHandler ZcalcTrapCompleted;
        
        /// <remarks/>
        public event ZactDiscMaximCompletedEventHandler ZactDiscMaximCompleted;
        
        /// <remarks/>
        public event ZgetPriceCompletedEventHandler ZgetPriceCompleted;
        
        /// <remarks/>
        public event ZstareComandaCompletedEventHandler ZstareComandaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZTBL_WEBSERVICE:ZcreazaComandaRe" +
            "quest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZcreazaComandaResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZcreazaComandaResponse ZcreazaComanda([System.Xml.Serialization.XmlElementAttribute("ZcreazaComanda", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZcreazaComanda ZcreazaComanda1) {
            object[] results = this.Invoke("ZcreazaComanda", new object[] {
                        ZcreazaComanda1});
            return ((ZcreazaComandaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZcreazaComandaAsync(ZcreazaComanda ZcreazaComanda1) {
            this.ZcreazaComandaAsync(ZcreazaComanda1, null);
        }
        
        /// <remarks/>
        public void ZcreazaComandaAsync(ZcreazaComanda ZcreazaComanda1, object userState) {
            if ((this.ZcreazaComandaOperationCompleted == null)) {
                this.ZcreazaComandaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZcreazaComandaOperationCompleted);
            }
            this.InvokeAsync("ZcreazaComanda", new object[] {
                        ZcreazaComanda1}, this.ZcreazaComandaOperationCompleted, userState);
        }
        
        private void OnZcreazaComandaOperationCompleted(object arg) {
            if ((this.ZcreazaComandaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZcreazaComandaCompleted(this, new ZcreazaComandaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZTBL_WEBSERVICE:ZcalcTrapRequest" +
            "", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZcalcTrapResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZcalcTrapResponse ZcalcTrap([System.Xml.Serialization.XmlElementAttribute("ZcalcTrap", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZcalcTrap ZcalcTrap1) {
            object[] results = this.Invoke("ZcalcTrap", new object[] {
                        ZcalcTrap1});
            return ((ZcalcTrapResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZcalcTrapAsync(ZcalcTrap ZcalcTrap1) {
            this.ZcalcTrapAsync(ZcalcTrap1, null);
        }
        
        /// <remarks/>
        public void ZcalcTrapAsync(ZcalcTrap ZcalcTrap1, object userState) {
            if ((this.ZcalcTrapOperationCompleted == null)) {
                this.ZcalcTrapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZcalcTrapOperationCompleted);
            }
            this.InvokeAsync("ZcalcTrap", new object[] {
                        ZcalcTrap1}, this.ZcalcTrapOperationCompleted, userState);
        }
        
        private void OnZcalcTrapOperationCompleted(object arg) {
            if ((this.ZcalcTrapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZcalcTrapCompleted(this, new ZcalcTrapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZTBL_WEBSERVICE:ZactDiscMaximReq" +
            "uest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZactDiscMaximResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZactDiscMaximResponse ZactDiscMaxim([System.Xml.Serialization.XmlElementAttribute("ZactDiscMaxim", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZactDiscMaxim ZactDiscMaxim1) {
            object[] results = this.Invoke("ZactDiscMaxim", new object[] {
                        ZactDiscMaxim1});
            return ((ZactDiscMaximResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZactDiscMaximAsync(ZactDiscMaxim ZactDiscMaxim1) {
            this.ZactDiscMaximAsync(ZactDiscMaxim1, null);
        }
        
        /// <remarks/>
        public void ZactDiscMaximAsync(ZactDiscMaxim ZactDiscMaxim1, object userState) {
            if ((this.ZactDiscMaximOperationCompleted == null)) {
                this.ZactDiscMaximOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZactDiscMaximOperationCompleted);
            }
            this.InvokeAsync("ZactDiscMaxim", new object[] {
                        ZactDiscMaxim1}, this.ZactDiscMaximOperationCompleted, userState);
        }
        
        private void OnZactDiscMaximOperationCompleted(object arg) {
            if ((this.ZactDiscMaximCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZactDiscMaximCompleted(this, new ZactDiscMaximCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZTBL_WEBSERVICE:ZgetPriceRequest" +
            "", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZgetPriceResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZgetPriceResponse ZgetPrice([System.Xml.Serialization.XmlElementAttribute("ZgetPrice", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZgetPrice ZgetPrice1) {
            object[] results = this.Invoke("ZgetPrice", new object[] {
                        ZgetPrice1});
            return ((ZgetPriceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZgetPriceAsync(ZgetPrice ZgetPrice1) {
            this.ZgetPriceAsync(ZgetPrice1, null);
        }
        
        /// <remarks/>
        public void ZgetPriceAsync(ZgetPrice ZgetPrice1, object userState) {
            if ((this.ZgetPriceOperationCompleted == null)) {
                this.ZgetPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZgetPriceOperationCompleted);
            }
            this.InvokeAsync("ZgetPrice", new object[] {
                        ZgetPrice1}, this.ZgetPriceOperationCompleted, userState);
        }
        
        private void OnZgetPriceOperationCompleted(object arg) {
            if ((this.ZgetPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZgetPriceCompleted(this, new ZgetPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZTBL_WEBSERVICE:ZstareComandaReq" +
            "uest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZstareComandaResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZstareComandaResponse ZstareComanda([System.Xml.Serialization.XmlElementAttribute("ZstareComanda", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZstareComanda ZstareComanda1) {
            object[] results = this.Invoke("ZstareComanda", new object[] {
                        ZstareComanda1});
            return ((ZstareComandaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZstareComandaAsync(ZstareComanda ZstareComanda1) {
            this.ZstareComandaAsync(ZstareComanda1, null);
        }
        
        /// <remarks/>
        public void ZstareComandaAsync(ZstareComanda ZstareComanda1, object userState) {
            if ((this.ZstareComandaOperationCompleted == null)) {
                this.ZstareComandaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZstareComandaOperationCompleted);
            }
            this.InvokeAsync("ZstareComanda", new object[] {
                        ZstareComanda1}, this.ZstareComandaOperationCompleted, userState);
        }
        
        private void OnZstareComandaOperationCompleted(object arg) {
            if ((this.ZstareComandaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZstareComandaCompleted(this, new ZstareComandaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcreazaComanda {
        
        private string canalField;
        
        private string faraTranspField;
        
        private string gvEventField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FaraTransp {
            get {
                return this.faraTranspField;
            }
            set {
                this.faraTranspField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvEvent {
            get {
                return this.gvEventField;
            }
            set {
                this.gvEventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcreazaComandaResponse {
        
        private string vMesajField;
        
        private string vOkField;
        
        private decimal vTransField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VMesaj {
            get {
                return this.vMesajField;
            }
            set {
                this.vMesajField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOk {
            get {
                return this.vOkField;
            }
            set {
                this.vOkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VTrans {
            get {
                return this.vTransField;
            }
            set {
                this.vTransField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcalcTrap {
        
        private string vCityField;
        
        private string vKunnrField;
        
        private decimal vNetwrField;
        
        private bool vNetwrFieldSpecified;
        
        private string vRegioField;
        
        private string vUlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCity {
            get {
                return this.vCityField;
            }
            set {
                this.vCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VKunnr {
            get {
                return this.vKunnrField;
            }
            set {
                this.vKunnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VNetwr {
            get {
                return this.vNetwrField;
            }
            set {
                this.vNetwrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VNetwrSpecified {
            get {
                return this.vNetwrFieldSpecified;
            }
            set {
                this.vNetwrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VRegio {
            get {
                return this.vRegioField;
            }
            set {
                this.vRegioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VUl {
            get {
                return this.vUlField;
            }
            set {
                this.vUlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcalcTrapResponse {
        
        private decimal vTrapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VTrap {
            get {
                return this.vTrapField;
            }
            set {
                this.vTrapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZactDiscMaxim {
        
        private string pattIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PattId {
            get {
                return this.pattIdField;
            }
            set {
                this.pattIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZactDiscMaximResponse {
        
        private string vOkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOk {
            get {
                return this.vOkField;
            }
            set {
                this.vOkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZgetPrice {
        
        private string canalField;
        
        private string cityField;
        
        private string dztermField;
        
        private decimal gvCantField;
        
        private bool gvCantFieldSpecified;
        
        private string gvKunnrField;
        
        private string gvLgortField;
        
        private string gvMatnrField;
        
        private string gvSiteField;
        
        private string gvSpartField;
        
        private string gvVrkmeField;
        
        private string gvWerksField;
        
        private string mpField;
        
        private string regioField;
        
        private string tipPersField;
        
        private string ulStocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dzterm {
            get {
                return this.dztermField;
            }
            set {
                this.dztermField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal GvCant {
            get {
                return this.gvCantField;
            }
            set {
                this.gvCantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GvCantSpecified {
            get {
                return this.gvCantFieldSpecified;
            }
            set {
                this.gvCantFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvKunnr {
            get {
                return this.gvKunnrField;
            }
            set {
                this.gvKunnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvLgort {
            get {
                return this.gvLgortField;
            }
            set {
                this.gvLgortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvMatnr {
            get {
                return this.gvMatnrField;
            }
            set {
                this.gvMatnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvSite {
            get {
                return this.gvSiteField;
            }
            set {
                this.gvSiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvSpart {
            get {
                return this.gvSpartField;
            }
            set {
                this.gvSpartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvVrkme {
            get {
                return this.gvVrkmeField;
            }
            set {
                this.gvVrkmeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvWerks {
            get {
                return this.gvWerksField;
            }
            set {
                this.gvWerksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mp {
            get {
                return this.mpField;
            }
            set {
                this.mpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Regio {
            get {
                return this.regioField;
            }
            set {
                this.regioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TipPers {
            get {
                return this.tipPersField;
            }
            set {
                this.tipPersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UlStoc {
            get {
                return this.ulStocField;
            }
            set {
                this.ulStocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZgetPriceResponse {
        
        private byte errorCodeField;
        
        private decimal gvCantField;
        
        private decimal gvCantFreeField;
        
        private string gvCondField;
        
        private string gvCurrencyField;
        
        private string gvMatnrFreeField;
        
        private decimal gvNetwrField;
        
        private decimal gvNetwrFreeField;
        
        private decimal gvNetwrListField;
        
        private string gvNoDiscField;
        
        private string gvVrkmeField;
        
        private string gvVrkmeFreeField;
        
        private string impachetField;
        
        private decimal multipluField;
        
        private decimal outCantUmbField;
        
        private string outUmbField;
        
        private decimal procTrapField;
        
        private string vMessField;
        
        private decimal valTrapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public byte ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal GvCant {
            get {
                return this.gvCantField;
            }
            set {
                this.gvCantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal GvCantFree {
            get {
                return this.gvCantFreeField;
            }
            set {
                this.gvCantFreeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvCond {
            get {
                return this.gvCondField;
            }
            set {
                this.gvCondField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvCurrency {
            get {
                return this.gvCurrencyField;
            }
            set {
                this.gvCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvMatnrFree {
            get {
                return this.gvMatnrFreeField;
            }
            set {
                this.gvMatnrFreeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal GvNetwr {
            get {
                return this.gvNetwrField;
            }
            set {
                this.gvNetwrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal GvNetwrFree {
            get {
                return this.gvNetwrFreeField;
            }
            set {
                this.gvNetwrFreeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal GvNetwrList {
            get {
                return this.gvNetwrListField;
            }
            set {
                this.gvNetwrListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvNoDisc {
            get {
                return this.gvNoDiscField;
            }
            set {
                this.gvNoDiscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvVrkme {
            get {
                return this.gvVrkmeField;
            }
            set {
                this.gvVrkmeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GvVrkmeFree {
            get {
                return this.gvVrkmeFreeField;
            }
            set {
                this.gvVrkmeFreeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Impachet {
            get {
                return this.impachetField;
            }
            set {
                this.impachetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Multiplu {
            get {
                return this.multipluField;
            }
            set {
                this.multipluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal OutCantUmb {
            get {
                return this.outCantUmbField;
            }
            set {
                this.outCantUmbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OutUmb {
            get {
                return this.outUmbField;
            }
            set {
                this.outUmbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ProcTrap {
            get {
                return this.procTrapField;
            }
            set {
                this.procTrapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VMess {
            get {
                return this.vMessField;
            }
            set {
                this.vMessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValTrap {
            get {
                return this.valTrapField;
            }
            set {
                this.valTrapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstareComanda {
        
        private string nrComField;
        
        private string pernrChField;
        
        private string stareField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NrCom {
            get {
                return this.nrComField;
            }
            set {
                this.nrComField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PernrCh {
            get {
                return this.pernrChField;
            }
            set {
                this.pernrChField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Stare {
            get {
                return this.stareField;
            }
            set {
                this.stareField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstareComandaResponse {
        
        private string vMessField;
        
        private string vOkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VMess {
            get {
                return this.vMessField;
            }
            set {
                this.vMessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOk {
            get {
                return this.vOkField;
            }
            set {
                this.vOkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ZcreazaComandaCompletedEventHandler(object sender, ZcreazaComandaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZcreazaComandaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZcreazaComandaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZcreazaComandaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZcreazaComandaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ZcalcTrapCompletedEventHandler(object sender, ZcalcTrapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZcalcTrapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZcalcTrapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZcalcTrapResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZcalcTrapResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ZactDiscMaximCompletedEventHandler(object sender, ZactDiscMaximCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZactDiscMaximCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZactDiscMaximCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZactDiscMaximResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZactDiscMaximResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ZgetPriceCompletedEventHandler(object sender, ZgetPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZgetPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZgetPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZgetPriceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZgetPriceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ZstareComandaCompletedEventHandler(object sender, ZstareComandaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZstareComandaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZstareComandaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZstareComandaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZstareComandaResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591