//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LiteSFATestWebService.SAPWSCustodie {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="zwbs_custodie", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class zwbs_custodie : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZcustChLivrareOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZlivrareCustodieOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public zwbs_custodie() {
            this.Url = global::LiteSFATestWebService.Properties.Settings.Default.LiteSFATestWebService_SAPWSCustodie_ZWS_CUSTODIE;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZcustChLivrareCompletedEventHandler ZcustChLivrareCompleted;
        
        /// <remarks/>
        public event ZlivrareCustodieCompletedEventHandler ZlivrareCustodieCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_CUSTODIE:ZcustChLivrareReque" +
            "st", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZcustChLivrareResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZcustChLivrareResponse ZcustChLivrare([System.Xml.Serialization.XmlElementAttribute("ZcustChLivrare", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZcustChLivrare ZcustChLivrare1) {
            object[] results = this.Invoke("ZcustChLivrare", new object[] {
                        ZcustChLivrare1});
            return ((ZcustChLivrareResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZcustChLivrareAsync(ZcustChLivrare ZcustChLivrare1) {
            this.ZcustChLivrareAsync(ZcustChLivrare1, null);
        }
        
        /// <remarks/>
        public void ZcustChLivrareAsync(ZcustChLivrare ZcustChLivrare1, object userState) {
            if ((this.ZcustChLivrareOperationCompleted == null)) {
                this.ZcustChLivrareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZcustChLivrareOperationCompleted);
            }
            this.InvokeAsync("ZcustChLivrare", new object[] {
                        ZcustChLivrare1}, this.ZcustChLivrareOperationCompleted, userState);
        }
        
        private void OnZcustChLivrareOperationCompleted(object arg) {
            if ((this.ZcustChLivrareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZcustChLivrareCompleted(this, new ZcustChLivrareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_CUSTODIE:ZlivrareCustodieReq" +
            "uest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZlivrareCustodieResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZlivrareCustodieResponse ZlivrareCustodie([System.Xml.Serialization.XmlElementAttribute("ZlivrareCustodie", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZlivrareCustodie ZlivrareCustodie1) {
            object[] results = this.Invoke("ZlivrareCustodie", new object[] {
                        ZlivrareCustodie1});
            return ((ZlivrareCustodieResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZlivrareCustodieAsync(ZlivrareCustodie ZlivrareCustodie1) {
            this.ZlivrareCustodieAsync(ZlivrareCustodie1, null);
        }
        
        /// <remarks/>
        public void ZlivrareCustodieAsync(ZlivrareCustodie ZlivrareCustodie1, object userState) {
            if ((this.ZlivrareCustodieOperationCompleted == null)) {
                this.ZlivrareCustodieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZlivrareCustodieOperationCompleted);
            }
            this.InvokeAsync("ZlivrareCustodie", new object[] {
                        ZlivrareCustodie1}, this.ZlivrareCustodieOperationCompleted, userState);
        }
        
        private void OnZlivrareCustodieOperationCompleted(object arg) {
            if ((this.ZlivrareCustodieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZlivrareCustodieCompleted(this, new ZlivrareCustodieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcustChLivrare {
        
        private string ipAdresaField;
        
        private string ipDataField;
        
        private string ipModeField;
        
        private string ipVbelnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IpAdresa {
            get {
                return this.ipAdresaField;
            }
            set {
                this.ipAdresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IpData {
            get {
                return this.ipDataField;
            }
            set {
                this.ipDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IpMode {
            get {
                return this.ipModeField;
            }
            set {
                this.ipModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IpVbeln {
            get {
                return this.ipVbelnField;
            }
            set {
                this.ipVbelnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcustChLivrareResponse {
        
        private string epMesajField;
        
        private string epOkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EpMesaj {
            get {
                return this.epMesajField;
            }
            set {
                this.epMesajField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EpOk {
            get {
                return this.epOkField;
            }
            set {
                this.epOkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZlivrareCustodie {
        
        private string ipIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IpId {
            get {
                return this.ipIdField;
            }
            set {
                this.ipIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZlivrareCustodieResponse {
        
        private string epMesajField;
        
        private string epOkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EpMesaj {
            get {
                return this.epMesajField;
            }
            set {
                this.epMesajField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EpOk {
            get {
                return this.epOkField;
            }
            set {
                this.epOkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ZcustChLivrareCompletedEventHandler(object sender, ZcustChLivrareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZcustChLivrareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZcustChLivrareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZcustChLivrareResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZcustChLivrareResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ZlivrareCustodieCompletedEventHandler(object sender, ZlivrareCustodieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZlivrareCustodieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZlivrareCustodieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZlivrareCustodieResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZlivrareCustodieResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591